[book]
title = "OmiChat"
authors = ["Omar M."]
description = "Documentation for the OmiChat Project Zomboid mod."
language = "en"
src = "docs"

[build]
build-dir = "guide"
use-default-preprocessors = false

[output.html]
git-repository-url = "https://github.com/omarkmu/pz-omichat"
site-url = "/pz-omichat/"
theme = "docs/theme"

[preprocessor.links]
