---Buffy preset.

local utils = require 'OmiChat/utils'
local Preset = require 'OmiChat/Component/Configuration/Preset'

local set = utils.set.simple


return Preset:new {
    name = 'Buffy',
    values = {
        General = {
            Preset = 'Buffy',
            AlwaysShowChat = false,
            CaseInsensitiveChatStreams = true,
            ClearOnDeath = set { 'Icon', 'Languages', 'Nickname' },
            MinimumCommandAccessLevel = 16,
            AdminIcon = 'Item_Hammer',
            InfoText = '',
        },
        Buffs = {
            Enable = true,
            Cooldown = 15,
            Boredom = 0.2,
            Unhappiness = 0.2,
            Hunger = 0.1,
            Thirst = 0.1,
            Fatigue = 0.1,
            CigaretteStress = 0.2,
        },
        Callouts = {
            Format = '$DefaultOverheadFormat()',
            SneakFormat = '$DefaultOverheadFormat()',
            Range = 48,
            SneakRange = 6,
        },
        Commands = {
            SetName = 'Nickname',
            Card = {
                Global = false,
                Format = '$DefaultCardFormat()',
                OverheadFormat = '$DefaultOverheadFormat()',
                ChatFormat = '$DefaultChatFormat()',
                Items = { 'CardDeck' },
                Tags = {},
            },
            Roll = {
                Global = false,
                Format = '$DefaultRollFormat()',
                OverheadFormat = '$DefaultOverheadFormat()',
                ChatFormat = '$DefaultChatFormat()',
                Items = {
                    'Dice',
                    'Dice_00',
                    'Dice_4',
                    'Dice_6',
                    'Dice_8',
                    'Dice_10',
                    'Dice_12',
                    'Dice_20',
                },
                Tags = {},
            },
            Flip = {
                Global = false,
                Format = '$DefaultFlipFormat()',
                OverheadFormat = '$DefaultOverheadFormat()',
                ChatFormat = '$DefaultChatFormat()',
                Items = {},
                Tags = {},
            },
        },
        Compatibility = {
            BuffyCharacterBios = 'Auto',
            BuffyRPGSystem = 'Auto',
            ChatBubble = 'Auto',
            SearchPlayers = 'Auto',
            TrueActionsDancing = 'Auto',
        },
        Customization = {
            AllowCustomShouts = true,
            EnableNameColors = true,
            EnableCharacterCustomization = true,
            CleanEffects = set { 'Body' },
        },
        Discord = {
            ChatFormat = '$DefaultChatFormat()',
            DefaultColor = { r = 144, g = 137, b = 218 },
            ShowColorOption = 'Respect_Server_Setting',
            Tags = {
                'UseAuthorUsername',
                'OOC' },
        },
        EchoMessages = {
            Enable = true,
            ChatFormat = '$DefaultChatFormat()',
            OverheadFormat = '$DefaultOverheadFormat()',
            Tags = {
                'OverRadio',
            },
        },
        Format = {
            Component = {
                Name = '$DefaultNameFormat()',
                Tag = '$DefaultTagFormat()',
                Timestamp = '$DefaultTimestampFormat()',
                Icon = '$DefaultIconFormat()',
                Language = '$DefaultLanguageFormat()',
                EmbeddedQuote = '$DefaultEmbeddedQuoteFormat()',
                EmbeddedAction = '$DefaultEmbeddedActionFormat()',
            },
            Overhead = {
                Final = '$DefaultFullOverheadFormat()',
                Prefix = '$DefaultOverheadPrefix()',
            },
            Chat = {
                Final = '$DefaultFullChatFormat()',
                Prefix = '$DefaultChatPrefix()',
            },
            Filter = {
                Name = '$DefaultNameFilter()',
                ChatInput = '$DefaultChatInputFilter()',
            },
            MenuName = {
                Default = '$DefaultMenuNameFormat()',
            },
        },
        Language = {
            UseDefaultList = true,
            List = {},
            DefaultSlots = 1,
            InterpretationRolls = 2,
            InterpretationChance = 25,
            UnknownLanguage = '$DefaultUnknownLanguageFormat()',
            UnknownLanguageRadio = '$DefaultUnknownLanguageFormat()',
            SelfAddAllowlist = {},
            SelfAddBlocklist = {},
        },
        Macros = {
            AllowEmotes = true,
        },
        NarrativeStyle = {
            Enable = true,
            OverheadContentFormat = '$DefaultNarrativeOverheadFormat()',
            ChatContentFormat = '$DefaultNarrativeChatFormat()',
            DialogueTagFormat = '$DefaultNarrativeTag()',
            InputFilter = '$DefaultNarrativeInputFilter()',
        },
        Radio = {
            ChatFormat = '$DefaultChatFormat()',
            DefaultColor = { r = 178, g = 178, b = 178 },
            Tags = {},
        },
        ServerMessages = {
            ChatFormat = '$DefaultChatFormat()',
            DefaultColor = { r = 0, g = 128, b = 255 },
            Tags = {
                'NoTimestamp',
            },
        },
        Streams = {
            UseDefaultList = false,
            GlobalTags = { 'UseActionAsterisks', 'IncludeName', 'IncludeAdminIndicator' },
            List = {
                {
                    Stream = 'admin',
                    Enable = true,
                    Tags = {
                        'NoIcon',
                        'NoAdminIndicator',
                    },
                },
                {
                    Stream = 'say',
                    Enable = true,
                    Range = 16,
                    DefaultColor = { r = 177, g = 210, b = 187 },
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'AutoColorActions',
                        'QuoteColorTarget',
                        'UseNameColor',
                    },
                },
                {
                    Stream = 'yell',
                    Enable = true,
                    Range = 48,
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'AutoColorActions',
                        'NoVolumeIndicator',
                        'Callout',
                        'Loud',
                        'UseNameColor',
                    },
                },
                {
                    Stream = 'low',
                    Enable = true,
                    Range = 4,
                    DefaultColor = { r = 177, g = 210, b = 187 },
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'AutoColorActions',
                        'EchoTarget',
                        'Quiet',
                        'UseNameColor',
                    },
                },
                {
                    Stream = 'whisper',
                    Enable = true,
                    Range = 2,
                    DefaultColor = { r = 177, g = 210, b = 187 },
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'AutoColorActions',
                        'Whisper',
                        'UseNameColor',
                    },
                },
                {
                    Stream = 'me',
                    Enable = true,
                    Range = 20,
                    DefaultColor = { r = 128, g = 0, b = 128 },
                    Tags = {
                        'AutoPunctuate',
                        'AutoColorQuotes',
                        'AutoCapitalizeEmbeddedQuotes',
                        'AutoCapitalizeNonInitialSegments',
                        'Action',
                        'NoAdminIndicator',
                        'NoIcon',
                        'ActionColorTarget',
                        'CardCommandTarget',
                        'FlipCommandTarget',
                        'RollCommandTarget',
                        'BuffyRPGTarget',
                        'UseNameColor',
                    },
                },
                {
                    Stream = 'meloud',
                    Aliases = { 'melong' },
                    Enable = true,
                    Range = 48,
                    DefaultColor = { r = 128, g = 0, b = 128 },
                    Tags = {
                        'AutoPunctuate',
                        'AutoColorQuotes',
                        'AutoCapitalizeEmbeddedQuotes',
                        'AutoCapitalizeNonInitialSegments',
                        'Action',
                        'NoAdminIndicator',
                        'NoIcon',
                        'Loud',
                        'UseNameColor',
                    },
                },
                {
                    Stream = 'mequiet',
                    Aliases = { 'melow' },
                    Enable = true,
                    Range = 4,
                    DefaultColor = { r = 128, g = 0, b = 128 },
                    Tags = {
                        'AutoPunctuate',
                        'AutoColorQuotes',
                        'AutoCapitalizeEmbeddedQuotes',
                        'AutoCapitalizeNonInitialSegments',
                        'Action',
                        'NoAdminIndicator',
                        'NoIcon',
                        'Quiet',
                        'UseNameColor',
                    },
                },
                {
                    Stream = 'mewhisper',
                    Enable = true,
                    DefaultColor = { r = 128, g = 0, b = 128 },
                    Tags = {
                        'AutoPunctuate',
                        'AutoColorQuotes',
                        'AutoCapitalizeEmbeddedQuotes',
                        'AutoCapitalizeNonInitialSegments',
                        'Action',
                        'NoAdminIndicator',
                        'NoIcon',
                        'Whisper',
                        'UseNameColor',
                    },
                },
                {
                    Stream = 'do',
                    Enable = true,
                    Range = 20,
                    DefaultColor = { r = 128, g = 0, b = 128 },
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'AutoColorQuotes',
                        'NoName',
                        'Action',
                        'NoAdminIndicator',
                        'NoIcon',
                    },
                },
                {
                    Stream = 'doloud',
                    Enable = true,
                    Range = 48,
                    DefaultColor = { r = 128, g = 0, b = 128 },
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'AutoColorQuotes',
                        'NoName',
                        'Action',
                        'NoAdminIndicator',
                        'NoIcon',
                        'Loud',
                    },
                },
                {
                    Stream = 'doquiet',
                    Aliases = { 'dolow' },
                    Enable = true,
                    Range = 4,
                    DefaultColor = { r = 128, g = 0, b = 128 },
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'AutoColorQuotes',
                        'NoName',
                        'Action',
                        'NoAdminIndicator',
                        'NoIcon',
                        'Quiet',
                    },
                },
                {
                    Stream = 'dowhisper',
                    Enable = true,
                    Range = 4,
                    DefaultColor = { r = 128, g = 0, b = 128 },
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'AutoColorQuotes',
                        'NoName',
                        'Action',
                        'NoAdminIndicator',
                        'NoIcon',
                        'Whisper',
                    },
                },
                {
                    Stream = 'ooc',
                    Enable = true,
                    Range = 20,
                    Tags = {
                        'OOC',
                        'NoNameOverhead',
                    },
                },
                {
                    Stream = 'private',
                    Enable = true,
                    ChatFormat = '$DefaultChatFormat()',
                    Tags = {
                        'UseNameColor',
                    },
                },
                {
                    Stream = 'faction',
                    Enable = true,
                    DefaultColor = { r = 22, g = 113, b = 20 },
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'OverRadio',
                        'NoSignedOverRadio',
                        'NoAdminIndicator',
                    },
                },
                {
                    Stream = 'safehouse',
                    Enable = true,
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'OverRadio',
                        'NoSignedOverRadio',
                        'NoAdminIndicator',
                    },
                },
                {
                    Stream = 'general',
                    Enable = true,
                    Tags = {
                        'OOC',
                    },
                },
            },
        },
        TypingIndicator = {
            Enable = true,
            Format = '$DefaultTypingFormat()',
        },
        ZombieAttraction = {
            ChatRangeMultiplier = 0,
            CalloutRange = 30,
            SneakCalloutRange = 6,
        },
    },
}
