---Buffy preset.

local Preset = require 'OmiChat/Component/Configuration/Preset'


return Preset:new {
    name = 'Buffy',
    settings = {
        PMParenCount = 2,
        VolumeIndicatorLoud = 'Long',

        DefaultNameMode = 'name',
        DefaultNameMode_admin = 'username',
        DefaultNameMode_whisper = 'both',
    },
    values = {
        General = Preset.general {
            Name = 'Buffy',
            AdminIcon = 'Item_Hammer',
        },
        Buffs = Preset.buffs {
            Enable = true,
        },
        Callouts = Preset.callouts {
            Range = 48,
        },
        Commands = Preset.commands(),
        Compatibility = Preset.compatibility(),
        Customization = Preset.customization {
            CleanEffects = { 'Body' },
        },
        Discord = Preset.discord {
            Tags = {
                'OOC',
                'UseAuthorUsername',
            },
        },
        EchoMessages = Preset.echo {
            Enable = true,
        },
        Format = Preset.format(),
        Language = Preset.languages(),
        Macros = Preset.macros(),
        NarrativeStyle = Preset.narrative {
            Enable = true,
        },
        Radio = Preset.radio(),
        ServerMessages = Preset.server {
            Tags = {
                'NoTimestamp',
            },
        },
        TypingIndicator = Preset.typing(),
        ZombieAttraction = Preset.zombies(),

        Streams = {
            UseDefaultList = false,
            GlobalTags = {
                'UseActionAsterisks',
                'IncludeName',
                'IncludeAdminIndicator',
            },
            List = {
                {
                    Stream = 'admin',
                    Enable = true,
                    Tags = {
                        'NoIcon',
                        'NoAdminIndicator',
                    },
                },
                {
                    Stream = 'say',
                    Enable = true,
                    Range = 16,
                    DefaultColor = { r = 177, g = 210, b = 187 },
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'AutoColorActions',
                        'QuoteColorTarget',
                        'UseNameColor',
                    },
                },
                {
                    Stream = 'yell',
                    Enable = true,
                    Range = 48,
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'AutoColorActions',
                        'NoVolumeIndicator',
                        'Callout',
                        'Loud',
                        'UseNameColor',
                    },
                },
                {
                    Stream = 'low',
                    Enable = true,
                    Range = 4,
                    PerceptionRange = 8,
                    DefaultColor = { r = 177, g = 210, b = 187 },
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'AutoColorActions',
                        'EchoTarget',
                        'Quiet',
                        'UseNameColor',
                    },
                },
                {
                    Stream = 'whisper',
                    Enable = true,
                    Range = 2,
                    PerceptionRange = 6,
                    DefaultColor = { r = 177, g = 210, b = 187 },
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'AutoColorActions',
                        'Whisper',
                        'UseNameColor',
                    },
                },
                {
                    Stream = 'me',
                    Enable = true,
                    Range = 20,
                    DefaultColor = { r = 128, g = 0, b = 128 },
                    Tags = {
                        'AutoPunctuate',
                        'AutoColorQuotes',
                        'AutoCapitalizeEmbeddedQuotes',
                        'AutoCapitalizeNonInitialSegments',
                        'Action',
                        'NoAdminIndicator',
                        'NoIcon',
                        'ActionColorTarget',
                        'CardCommandTarget',
                        'FlipCommandTarget',
                        'RollCommandTarget',
                        'BuffyRPGTarget',
                        'UseNameColor',
                    },
                },
                {
                    Stream = 'meloud',
                    Aliases = { 'melong' },
                    Enable = true,
                    Range = 48,
                    DefaultColor = { r = 128, g = 0, b = 128 },
                    Tags = {
                        'AutoPunctuate',
                        'AutoColorQuotes',
                        'AutoCapitalizeEmbeddedQuotes',
                        'AutoCapitalizeNonInitialSegments',
                        'Action',
                        'NoAdminIndicator',
                        'NoIcon',
                        'Loud',
                        'UseNameColor',
                    },
                },
                {
                    Stream = 'mequiet',
                    Aliases = { 'melow' },
                    Enable = true,
                    Range = 4,
                    DefaultColor = { r = 128, g = 0, b = 128 },
                    Tags = {
                        'AutoPunctuate',
                        'AutoColorQuotes',
                        'AutoCapitalizeEmbeddedQuotes',
                        'AutoCapitalizeNonInitialSegments',
                        'Action',
                        'NoAdminIndicator',
                        'NoIcon',
                        'Quiet',
                        'UseNameColor',
                    },
                },
                {
                    Stream = 'mewhisper',
                    Enable = true,
                    DefaultColor = { r = 128, g = 0, b = 128 },
                    Tags = {
                        'AutoPunctuate',
                        'AutoColorQuotes',
                        'AutoCapitalizeEmbeddedQuotes',
                        'AutoCapitalizeNonInitialSegments',
                        'Action',
                        'NoAdminIndicator',
                        'NoIcon',
                        'Whisper',
                        'UseNameColor',
                    },
                },
                {
                    Stream = 'do',
                    Enable = true,
                    Range = 20,
                    DefaultColor = { r = 128, g = 0, b = 128 },
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'AutoColorQuotes',
                        'NoName',
                        'Action',
                        'NoAdminIndicator',
                        'NoIcon',
                    },
                },
                {
                    Stream = 'doloud',
                    Enable = true,
                    Range = 48,
                    DefaultColor = { r = 128, g = 0, b = 128 },
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'AutoColorQuotes',
                        'NoName',
                        'Action',
                        'NoAdminIndicator',
                        'NoIcon',
                        'Loud',
                    },
                },
                {
                    Stream = 'doquiet',
                    Aliases = { 'dolow' },
                    Enable = true,
                    Range = 4,
                    DefaultColor = { r = 128, g = 0, b = 128 },
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'AutoColorQuotes',
                        'NoName',
                        'Action',
                        'NoAdminIndicator',
                        'NoIcon',
                        'Quiet',
                    },
                },
                {
                    Stream = 'dowhisper',
                    Enable = true,
                    Range = 4,
                    DefaultColor = { r = 128, g = 0, b = 128 },
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'AutoColorQuotes',
                        'NoName',
                        'Action',
                        'NoAdminIndicator',
                        'NoIcon',
                        'Whisper',
                    },
                },
                {
                    Stream = 'ooc',
                    Enable = true,
                    Range = 20,
                    Tags = {
                        'OOC',
                        'NoNameOverhead',
                    },
                },
                {
                    Stream = 'private',
                    Enable = true,
                    Tags = {
                        'UseNameColor',
                    },
                },
                {
                    Stream = 'faction',
                    Enable = true,
                    DefaultColor = { r = 22, g = 113, b = 20 },
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'OverRadio',
                        'NoSignedOverRadio',
                        'NoAdminIndicator',
                    },
                },
                {
                    Stream = 'safehouse',
                    Enable = true,
                    Tags = {
                        'AutoCapitalize',
                        'AutoPunctuate',
                        'OverRadio',
                        'NoSignedOverRadio',
                        'NoAdminIndicator',
                    },
                },
                {
                    Stream = 'general',
                    Enable = true,
                    Tags = {
                        'OOC',
                    },
                },
            },
        },
    },
}
