---Default configuration data for built-in streams.
---@namespace omichat

local DEFAULT = '$Default()'


---@type table<string, Configuration.StreamDefinition>
local DefaultStreamData = {
    admin = {
        ChatType = 'admin',
        Category = 'chat',
        Command = '/admin',
        ShortCommand = '/a',
        AllowMentions = true,
        DefaultColor = { r = 210, g = 210, b = 210 },
        ChatFormat = DEFAULT,
        Tags = {
            'NoIcon',
            'NoAdminIndicator',
        },
    },
    say = {
        ChatType = 'say',
        Category = 'chat',
        Command = '/say',
        ShortCommand = '/s',
        DefaultColor = { r = 177, g = 210, b = 187 },
        Range = 16,
        RangeSigned = 0,
        VerticalRange = 2,
        VerticalRangeSigned = 1,
        PerceptionRange = 0,
        PerceptionRangeSigned = 0,
        AllowMentions = true,
        AllowLanguages = true,
        AllowTypingIndicator = true,
        AttractZombies = true,
        UseNarrativeStyle = true,
        OverheadFormat = DEFAULT,
        ChatFormat = DEFAULT,
        Tags = {
            'AutoCapitalizeNarrative',
            'AutoPunctuateNarrative',
            'AutoColorActions',
            'QuoteColorTarget',
            'UseNameColor',
        },
    },
    yell = {
        ChatType = 'shout',
        Category = 'chat',
        Command = '/yell',
        ShortCommand = '/y',
        Aliases = { 'shout' },
        DefaultColor = { r = 255, g = 51, b = 51 },
        Range = 48,
        RangeSigned = 0,
        VerticalRange = 3,
        VerticalRangeSigned = 1,
        PerceptionRange = 0,
        PerceptionRangeSigned = 0,
        AllowMentions = true,
        AllowLanguages = true,
        AllowTypingIndicator = true,
        AttractZombies = true,
        UseNarrativeStyle = true,
        OverheadFormat = DEFAULT,
        ChatFormat = DEFAULT,
        Tags = {
            'AutoCapitalizeNarrative',
            'AutoPunctuateNarrative',
            'AutoColorActions',
            'NoVolumeIndicator',
            'Loud',
            'Callout',
            'UseNameColor',
        },
    },
    low = {
        ChatType = 'say',
        Category = 'chat',
        Command = '/low',
        ShortCommand = '/l',
        DefaultColor = { r = 177, g = 210, b = 187 },
        Range = 4,
        RangeSigned = 0,
        VerticalRange = 1,
        VerticalRangeSigned = 1,
        PerceptionRange = 8,
        PerceptionRangeSigned = 10,
        AllowMentions = true,
        AllowLanguages = true,
        AllowTypingIndicator = true,
        UseNarrativeStyle = true,
        OverheadFormat = DEFAULT,
        ChatFormat = DEFAULT,
        Tags = {
            'AutoCapitalizeNarrative',
            'AutoPunctuateNarrative',
            'AutoColorActions',
            'Quiet',
            'EchoTarget',
            'UseNameColor',
        },
    },
    whisper = {
        ChatType = 'say',
        Category = 'chat',
        Command = '/whisper',
        ShortCommand = '/w',
        DefaultColor = { r = 177, g = 210, b = 187 },
        Range = 2,
        RangeSigned = 0,
        VerticalRange = 1,
        VerticalRangeSigned = 1,
        PerceptionRange = 6,
        PerceptionRangeSigned = 8,
        AllowMentions = true,
        AllowLanguages = true,
        AllowTypingIndicator = true,
        UseNarrativeStyle = true,
        OverheadFormat = DEFAULT,
        ChatFormat = DEFAULT,
        Tags = {
            'AutoCapitalizeNarrative',
            'AutoPunctuateNarrative',
            'AutoColorActions',
            'Whisper',
            'UseNameColor',
        },
    },
    me = {
        ChatType = 'say',
        Category = 'rp',
        Command = '/me',
        ShortCommand = '/m',
        DefaultColor = { r = 128, g = 0, b = 128 },
        Range = 20,
        RangeSigned = 0,
        VerticalRange = 2,
        VerticalRangeSigned = 1,
        PerceptionRange = 0,
        PerceptionRangeSigned = 0,
        AllowBuffs = true,
        AllowMentions = true,
        AllowTypingIndicator = true,
        OverheadFormat = DEFAULT,
        ChatFormat = DEFAULT,
        Tags = {
            'AutoPunctuate',
            'AutoColorQuotes',
            'AutoCapitalizeEmbeddedQuotes',
            'AutoCapitalizeNonInitialSegments',
            'Action',
            'NoAdminIndicator',
            'NoIcon',
            'ActionColorTarget',
            'CardCommandTarget',
            'FlipCommandTarget',
            'RollCommandTarget',
            'UseNameColor',
        },
    },
    meloud = {
        ChatType = 'shout',
        Category = 'rp',
        Command = '/meloud',
        ShortCommand = '/ml',
        Aliases = { 'melong' },
        DefaultColor = { r = 128, g = 0, b = 128 },
        Range = 48,
        RangeSigned = 0,
        VerticalRange = 3,
        VerticalRangeSigned = 1,
        PerceptionRange = 0,
        PerceptionRangeSigned = 0,
        AllowBuffs = true,
        AllowMentions = true,
        AllowTypingIndicator = true,
        AttractZombies = true,
        OverheadFormat = DEFAULT,
        ChatFormat = DEFAULT,
        Tags = {
            'AutoPunctuate',
            'AutoColorQuotes',
            'AutoCapitalizeEmbeddedQuotes',
            'AutoCapitalizeNonInitialSegments',
            'Action',
            'NoAdminIndicator',
            'NoIcon',
            'Loud',
            'UseNameColor',
        },
    },
    mequiet = {
        ChatType = 'say',
        Category = 'rp',
        Command = '/mequiet',
        ShortCommand = '/mq',
        Aliases = { 'melow' },
        DefaultColor = { r = 128, g = 0, b = 128 },
        Range = 4,
        RangeSigned = 0,
        VerticalRange = 1,
        VerticalRangeSigned = 1,
        PerceptionRange = 0,
        PerceptionRangeSigned = 0,
        AllowBuffs = true,
        AllowMentions = true,
        AllowTypingIndicator = true,
        OverheadFormat = DEFAULT,
        ChatFormat = DEFAULT,
        Tags = {
            'AutoPunctuate',
            'AutoColorQuotes',
            'AutoCapitalizeEmbeddedQuotes',
            'AutoCapitalizeNonInitialSegments',
            'Action',
            'NoAdminIndicator',
            'NoIcon',
            'Quiet',
            'UseNameColor',
        },
    },
    mewhisper = {
        ChatType = 'say',
        Category = 'rp',
        Command = '/mewhisper',
        ShortCommand = '/mw',
        DefaultColor = { r = 128, g = 0, b = 128 },
        Range = 2,
        RangeSigned = 0,
        VerticalRange = 1,
        VerticalRangeSigned = 1,
        PerceptionRange = 0,
        PerceptionRangeSigned = 0,
        AllowBuffs = true,
        AllowMentions = true,
        AllowTypingIndicator = true,
        OverheadFormat = DEFAULT,
        ChatFormat = DEFAULT,
        Tags = {
            'AutoPunctuate',
            'AutoColorQuotes',
            'AutoCapitalizeEmbeddedQuotes',
            'AutoCapitalizeNonInitialSegments',
            'Action',
            'NoAdminIndicator',
            'NoIcon',
            'Whisper',
            'UseNameColor',
        },
    },
    ['do'] = {
        ChatType = 'say',
        Category = 'rp',
        Command = '/do',
        ShortCommand = '/d',
        DefaultColor = { r = 128, g = 0, b = 128 },
        Range = 20,
        RangeSigned = 0,
        VerticalRange = 2,
        VerticalRangeSigned = 1,
        PerceptionRange = 0,
        PerceptionRangeSigned = 0,
        AllowMentions = true,
        AllowTypingIndicator = true,
        OverheadFormat = DEFAULT,
        ChatFormat = DEFAULT,
        Tags = {
            'AutoCapitalize',
            'AutoPunctuate',
            'AutoColorQuotes',
            'NoName',
            'Action',
            'NoAdminIndicator',
            'NoIcon',
        },
    },
    doloud = {
        ChatType = 'shout',
        Category = 'rp',
        Command = '/doloud',
        ShortCommand = '/dl',
        DefaultColor = { r = 128, g = 0, b = 128 },
        Range = 48,
        RangeSigned = 0,
        VerticalRange = 3,
        VerticalRangeSigned = 1,
        PerceptionRange = 0,
        PerceptionRangeSigned = 0,
        AllowMentions = true,
        AllowTypingIndicator = true,
        AttractZombies = true,
        OverheadFormat = DEFAULT,
        ChatFormat = DEFAULT,
        Tags = {
            'AutoCapitalize',
            'AutoPunctuate',
            'AutoColorQuotes',
            'NoName',
            'Action',
            'NoAdminIndicator',
            'NoIcon',
            'Loud',
        },
    },
    doquiet = {
        ChatType = 'say',
        Category = 'rp',
        Command = '/doquiet',
        ShortCommand = '/dq',
        Aliases = { 'dolow' },
        DefaultColor = { r = 128, g = 0, b = 128 },
        Range = 4,
        RangeSigned = 0,
        VerticalRange = 2,
        VerticalRangeSigned = 1,
        PerceptionRange = 0,
        PerceptionRangeSigned = 0,
        AllowMentions = true,
        AllowTypingIndicator = true,
        OverheadFormat = DEFAULT,
        ChatFormat = DEFAULT,
        Tags = {
            'AutoCapitalize',
            'AutoPunctuate',
            'AutoColorQuotes',
            'NoName',
            'Action',
            'NoAdminIndicator',
            'NoIcon',
            'Quiet',
        },
    },
    dowhisper = {
        ChatType = 'say',
        Category = 'rp',
        Command = '/dowhisper',
        ShortCommand = '/dw',
        DefaultColor = { r = 128, g = 0, b = 128 },
        Range = 2,
        RangeSigned = 0,
        VerticalRange = 1,
        VerticalRangeSigned = 1,
        PerceptionRange = 0,
        PerceptionRangeSigned = 0,
        AllowBuffs = true,
        AllowMentions = true,
        AllowTypingIndicator = true,
        OverheadFormat = DEFAULT,
        ChatFormat = DEFAULT,
        Tags = {
            'AutoCapitalize',
            'AutoPunctuate',
            'AutoColorQuotes',
            'NoName',
            'Action',
            'NoAdminIndicator',
            'NoIcon',
            'Whisper',
        },
    },
    ooc = {
        ChatType = 'say',
        Category = 'chat',
        Command = '/ooc',
        ShortCommand = '/o',
        DefaultColor = { r = 48, g = 128, b = 128 },
        Range = 20,
        RangeSigned = 0,
        VerticalRange = 2,
        VerticalRangeSigned = 1,
        PerceptionRange = 0,
        PerceptionRangeSigned = 0,
        AllowMentions = true,
        AllowTypingIndicator = true,
        OverheadFormat = DEFAULT,
        ChatFormat = DEFAULT,
        Tags = {
            'OOC',
            'NoNameOverhead',
        },
    },
    private = {
        ChatType = 'whisper',
        Category = 'chat',
        Command = '/pm',
        DefaultColor = { r = 85, g = 26, b = 139 },
        AllowMentions = false,
        ChatFormat = DEFAULT,
        Tags = {
            'UseNameColor',
        },
    },
    faction = {
        ChatType = 'faction',
        Category = 'chat',
        Command = '/faction',
        ShortCommand = '/f',
        DefaultColor = { r = 22, g = 113, b = 20 },
        AllowLanguages = true,
        AllowMentions = true,
        UseNarrativeStyle = true,
        ChatFormat = DEFAULT,
        Tags = {
            'AutoCapitalize',
            'AutoPunctuate',
            'OverRadio',
            'NoSignedOverRadio',
            'NoAdminIndicator',
        },
    },
    safehouse = {
        ChatType = 'safehouse',
        Category = 'chat',
        Command = '/safehouse',
        ShortCommand = '/sh',
        DefaultColor = { r = 55, g = 148, b = 53 },
        AllowLanguages = true,
        AllowMentions = true,
        UseNarrativeStyle = true,
        ChatFormat = DEFAULT,
        Tags = {
            'AutoCapitalize',
            'AutoPunctuate',
            'OverRadio',
            'NoSignedOverRadio',
            'NoAdminIndicator',
        },
    },
    general = {
        ChatType = 'general',
        Category = 'chat',
        Command = '/all',
        DefaultColor = { r = 255, g = 165, b = 0 },
        AllowMentions = true,
        ChatFormat = DEFAULT,
        Tags = {
            'OOC',
        },
    },
    narrate = {
        ChatType = 'say',
        Category = 'rp',
        Command = '/narrate',
        ShortCommand = '/nr',
        DefaultColor = { r = 102, g = 204, b = 153 },
        Range = 16,
        RangeSigned = 0,
        VerticalRange = 2,
        VerticalRangeSigned = 1,
        PerceptionRange = 0,
        PerceptionRangeSigned = 0,
        AllowMentions = true,
        AllowLanguages = false,
        AllowTypingIndicator = false,
        AttractZombies = false,
        UseNarrativeStyle = false,
        OverheadFormat = DEFAULT,
        ChatFormat = DEFAULT,
        Roles = {
            'admin',
            'moderator',
            'gm',
        },
        Tags = {
            'NoName',
            'NoEmbeddedActions',
            'HideOverhead',
            'DoubleBracketedText',
            'AutoCapitalize',
            'AutoPunctuate',
            'IgnoreRolesForCustomize',
        },
    },
}

return DefaultStreamData
