---@type table<string, omichat.ChatStream>
return {
    ooc = {
        name = 'ooc',
        command = '/ooc ',
        shortCommand = '/o ',
        tabID = 1,
        omichat = {
            allowEmotes = true,
            allowIconPicker = true,
            commandType = 'chat',
            formatter = 'ooc',
        },
    },
    low = {
        name = 'low',
        command = '/low ',
        shortCommand = '/l ',
        tabID = 1,
        omichat = {
            allowEmotes = true,
            allowIconPicker = true,
            commandType = 'chat',
            formatter = 'low',
        },
    },
    whisper = {
        name = 'whisper',
        command = '/whisper ',
        shortCommand = '/w ',
        tabID = 1,
        omichat = {
            allowEmotes = true,
            allowIconPicker = true,
            isLocalWhisper = true,
            commandType = 'chat',
            formatter = 'whisper',
        },
    },
    ['do'] = {
        name = 'do',
        command = '/do ',
        shortCommand = '/d ',
        tabID = 1,
        omichat = {
            allowEmotes = true,
            allowIconPicker = true,
            commandType = 'rp',
            formatter = 'do',
        },
    },
    doquiet = {
        name = 'doquiet',
        command = '/doquiet ',
        shortCommand = '/dq ',
        tabID = 1,
        omichat = {
            allowEmotes = true,
            allowIconPicker = true,
            commandType = 'rp',
            formatter = 'doquiet',
            aliases = { '/dolow ' },
        },
    },
    doloud = {
        name = 'doloud',
        command = '/doloud ',
        shortCommand = '/dl ',
        tabID = 1,
        omichat = {
            allowEmotes = true,
            allowIconPicker = false,
            commandType = 'rp',
            chatType = 'shout',
            formatter = 'doloud',
            aliases = { '/dolong ' },
        },
    },
    me = {
        name = 'me',
        command = '/me ',
        shortCommand = '/m ',
        tabID = 1,
        omichat = {
            allowEmotes = true,
            allowIconPicker = true,
            commandType = 'rp',
            formatter = 'me',
        },
    },
    mequiet = {
        name = 'mequiet',
        command = '/mequiet ',
        shortCommand = '/mq ',
        tabID = 1,
        omichat = {
            allowEmotes = true,
            allowIconPicker = true,
            commandType = 'rp',
            formatter = 'mequiet',
            aliases = { '/melow ' },
        },
    },
    meloud = {
        name = 'meloud',
        command = '/meloud ',
        shortCommand = '/ml ',
        tabID = 1,
        omichat = {
            allowEmotes = true,
            allowIconPicker = false,
            commandType = 'rp',
            chatType = 'shout',
            formatter = 'meloud',
            aliases = { '/melong ' },
        },
    },
}
