---Default configuration data for built-in streams.

---@type omichat.Configuration.StreamDefinition[]
return {
    admin = {
        ChatType = 'admin',
        CommandType = 'chat',
        Command = '/admin',
        ShortCommand = '/a',
        DefaultColor = { r = 210, g = 210, b = 210 },
        ChatFormat = '$DefaultChatFormat()',
        Tags = {
            'NoIcon',
            'NoAdminIndicator',
        },
    },
    say = {
        ChatType = 'say',
        CommandType = 'chat',
        Command = '/say',
        ShortCommand = '/s',
        DefaultColor = { r = 210, g = 210, b = 210 },
        Range = 30,
        VerticalRange = 2,
        AllowEmotes = true,
        AllowLanguages = true,
        AllowTypingIndicator = true,
        AttractZombies = true,
        UseNarrativeStyle = true,
        OverheadFormat = '$DefaultOverheadFormat()',
        ChatFormat = '$DefaultChatFormat()',
        Tags = {
            'AutoCapitalizeNarrative',
            'AutoPunctuateNarrative',
            'QuoteColorTarget',
            'UseNameColor',
        },
    },
    yell = {
        ChatType = 'shout',
        CommandType = 'chat',
        Command = '/yell',
        ShortCommand = '/y',
        Aliases = { 'shout' },
        DefaultColor = { r = 255, g = 51, b = 51 },
        Range = 60,
        VerticalRange = 3,
        AllowEmotes = true,
        AllowLanguages = true,
        AllowTypingIndicator = true,
        AttractZombies = true,
        UseNarrativeStyle = true,
        OverheadFormat = '$DefaultOverheadFormat()',
        ChatFormat = '$DefaultChatFormat()',
        Tags = {
            'AutoCapitalizeNarrative',
            'AutoPunctuateNarrative',
            'NoVolumeIndicator',
            'Loud',
            'Callout',
        },
    },
    low = {
        ChatType = 'say',
        CommandType = 'chat',
        Command = '/low',
        ShortCommand = '/l',
        DefaultColor = { r = 85, g = 48, b = 139 },
        Range = 5,
        VerticalRange = 1,
        AllowEmotes = true,
        AllowLanguages = true,
        AllowTypingIndicator = true,
        UseNarrativeStyle = true,
        OverheadFormat = '$DefaultOverheadFormat()',
        ChatFormat = '$DefaultChatFormat()',
        Tags = {
            'AutoCapitalizeNarrative',
            'AutoPunctuateNarrative',
            'Quiet',
            'EchoTarget',
        },
    },
    whisper = {
        ChatType = 'say',
        CommandType = 'chat',
        Command = '/whisper',
        ShortCommand = '/w',
        DefaultColor = { r = 85, g = 48, b = 139 },
        Range = 2,
        VerticalRange = 1,
        AllowEmotes = true,
        AllowLanguages = true,
        AllowTypingIndicator = true,
        UseNarrativeStyle = true,
        OverheadFormat = '$DefaultOverheadFormat()',
        ChatFormat = '$DefaultChatFormat()',
        Tags = {
            'AutoCapitalizeNarrative',
            'AutoPunctuateNarrative',
            'Whisper',
        },
    },
    me = {
        ChatType = 'say',
        CommandType = 'rp',
        Command = '/me',
        ShortCommand = '/m',
        DefaultColor = { r = 130, g = 130, b = 130 },
        Range = 30,
        VerticalRange = 2,
        AllowBuffs = true,
        AllowEmotes = true,
        AllowTypingIndicator = true,
        OverheadFormat = '$DefaultOverheadFormat()',
        ChatFormat = '$DefaultChatFormat()',
        Tags = {
            'AutoPunctuateChat',
            'AutoColorQuotes',
            'Action',
            'IncludeName',
            'ActionColorTarget',
            'CardCommandTarget',
            'FlipCommandTarget',
            'RollCommandTarget',
            'BuffyRPGTarget',
            'UseNameColor',
        },
    },
    meloud = {
        ChatType = 'shout',
        CommandType = 'rp',
        Command = '/meloud',
        ShortCommand = '/ml',
        DefaultColor = { r = 130, g = 130, b = 130 },
        Range = 60,
        VerticalRange = 3,
        AllowBuffs = true,
        AllowEmotes = true,
        AllowTypingIndicator = true,
        AttractZombies = true,
        OverheadFormat = '$DefaultOverheadFormat()',
        ChatFormat = '$DefaultChatFormat()',
        Tags = {
            'AutoPunctuateChat',
            'AutoColorQuotes',
            'Action',
            'IncludeName',
            'Loud',
            'UseNameColor',
        },
    },
    mequiet = {
        ChatType = 'say',
        CommandType = 'rp',
        Command = '/mequiet',
        ShortCommand = '/mq',
        DefaultColor = { r = 130, g = 130, b = 130 },
        Range = 5,
        VerticalRange = 1,
        AllowBuffs = true,
        AllowEmotes = true,
        AllowTypingIndicator = true,
        OverheadFormat = '$DefaultOverheadFormat()',
        ChatFormat = '$DefaultChatFormat()',
        Tags = {
            'AutoPunctuateChat',
            'AutoColorQuotes',
            'Action',
            'IncludeName',
            'Quiet',
            'UseNameColor',
        },
    },
    mewhisper = {
        ChatType = 'say',
        CommandType = 'rp',
        Command = '/mewhisper',
        ShortCommand = '/mw',
        DefaultColor = { r = 130, g = 130, b = 130 },
        Range = 2,
        VerticalRange = 1,
        AllowBuffs = true,
        AllowEmotes = true,
        AllowTypingIndicator = true,
        OverheadFormat = '$DefaultOverheadFormat()',
        ChatFormat = '$DefaultChatFormat()',
        Tags = {
            'AutoPunctuateChat',
            'AutoColorQuotes',
            'Action',
            'IncludeName',
            'Whisper',
            'UseNameColor',
        },
    },
    ['do'] = {
        ChatType = 'say',
        CommandType = 'rp',
        Command = '/do',
        ShortCommand = '/d',
        DefaultColor = { r = 130, g = 130, b = 130 },
        Range = 30,
        VerticalRange = 2,
        AllowEmotes = true,
        AllowTypingIndicator = true,
        OverheadFormat = '$DefaultOverheadFormat()',
        ChatFormat = '$DefaultChatFormat()',
        Tags = {
            'AutoCapitalizeNarrative',
            'AutoCapitalizeChat',
            'AutoPunctuateChat',
            'AutoColorQuotes',
            'NoName',
            'Action',
            'UseNameColor',
        },
    },
    doloud = {
        ChatType = 'shout',
        CommandType = 'rp',
        Command = '/doloud',
        ShortCommand = '/dl',
        DefaultColor = { r = 130, g = 130, b = 130 },
        Range = 60,
        VerticalRange = 3,
        AllowEmotes = true,
        AllowTypingIndicator = true,
        AttractZombies = true,
        OverheadFormat = '$DefaultOverheadFormat()',
        ChatFormat = '$DefaultChatFormat()',
        Tags = {
            'AutoCapitalizeNarrative',
            'AutoCapitalizeChat',
            'AutoPunctuateChat',
            'AutoColorQuotes',
            'NoName',
            'Action',
            'Loud',
            'UseNameColor',
        },
    },
    doquiet = {
        ChatType = 'say',
        CommandType = 'rp',
        Command = '/doquiet',
        ShortCommand = '/dq',
        DefaultColor = { r = 130, g = 130, b = 130 },
        Range = 5,
        VerticalRange = 2,
        AllowEmotes = true,
        AllowTypingIndicator = true,
        OverheadFormat = '$DefaultOverheadFormat()',
        ChatFormat = '$DefaultChatFormat()',
        Tags = {
            'AutoCapitalizeNarrative',
            'AutoCapitalizeChat',
            'AutoPunctuateChat',
            'AutoColorQuotes',
            'NoName',
            'Action',
            'Quiet',
            'UseNameColor',
        },
    },
    dowhisper = {
        ChatType = 'say',
        CommandType = 'rp',
        Command = '/dowhisper',
        ShortCommand = '/dw',
        DefaultColor = { r = 130, g = 130, b = 130 },
        Range = 2,
        VerticalRange = 1,
        AllowBuffs = true,
        AllowEmotes = true,
        AllowTypingIndicator = true,
        OverheadFormat = '$DefaultOverheadFormat()',
        ChatFormat = '$DefaultChatFormat()',
        Tags = {
            'AutoCapitalizeNarrative',
            'AutoCapitalizeChat',
            'AutoPunctuateChat',
            'AutoColorQuotes',
            'NoName',
            'Action',
            'Whisper',
            'UseNameColor',
        },
    },
    ooc = {
        ChatType = 'say',
        CommandType = 'chat',
        Command = '/ooc',
        ShortCommand = '/o',
        DefaultColor = { r = 48, g = 128, b = 128 },
        Range = 30,
        VerticalRange = 2,
        AllowEmotes = true,
        AllowTypingIndicator = true,
        OverheadFormat = '$DefaultOverheadFormat()',
        ChatFormat = '$DefaultChatFormat()',
        Tags = {
            'OOC',
            'NoNameOverhead',
        },
    },
    private = {
        ChatType = 'whisper',
        CommandType = 'chat',
        Command = '/pm',
        DefaultColor = { r = 85, g = 26, b = 139 },
        ChatFormat = '$DefaultChatFormat()',
    },
    faction = {
        ChatType = 'faction',
        CommandType = 'chat',
        Command = '/faction',
        ShortCommand = '/f',
        DefaultColor = { r = 22, g = 113, b = 20 },
        AllowLanguages = true,
        UseNarrativeStyle = true,
        ChatFormat = '$DefaultChatFormat()',
        Tags = {
            'AutoCapitalizeNarrative',
            'AutoPunctuateNarrative',
        },
    },
    safehouse = {
        ChatType = 'safehouse',
        CommandType = 'chat',
        Command = '/safehouse',
        ShortCommand = '/sh',
        DefaultColor = { r = 55, g = 148, b = 53 },
        AllowLanguages = true,
        UseNarrativeStyle = true,
        ChatFormat = '$DefaultChatFormat()',
        Tags = {
            'AutoCapitalizeNarrative',
            'AutoPunctuateNarrative',
        },
    },
    general = {
        ChatType = 'general',
        CommandType = 'chat',
        Command = '/all',
        DefaultColor = { r = 255, g = 165, b = 0 },
        ChatFormat = '$DefaultChatFormat()',
    },
}
