name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: '.'
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install latest mdbook
        run: |
          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook
          curl -sSL $url | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH
      - name: Install Lua language server
        run: |
          tag=$(curl 'https://api.github.com/repos/LuaLS/lua-language-server/releases/latest' | jq -r '.tag_name')
          url="https://github.com/LuaLS/lua-language-server/releases/download/${tag}/lua-language-server-${tag}-linux-x64.tar.gz"
          mkdir lls
          curl -sSL $url | tar -xz --directory=./lls
          echo `pwd`/lls/bin >> $GITHUB_PATH
      - name: Run pre-deploy script
        run: ./scripts/predeploy.sh
      - name: Build Book
        run: mdbook build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'guide'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
