name: Update

permissions: write-all

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  library:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: dev
        path: '.'
    - name: Checkout library
      uses: actions/checkout@v4
      with:
        path: OmiLibrary
        repository: omarkmu/pz-library
    - name: Read library version
      id: read_version
      run: |
        version=`cat OmiLibrary/library.json | jq -r '.version'`
        echo "version=$version" >> $GITHUB_OUTPUT
    - name: Build library
      run: |
        OmiLibrary/scripts/build.sh
        OmiLibrary/scripts/bundle.sh -m ${{ vars.LIB_MODULES }} -o ${{ vars.LIB_PATH }}
    - name: Create pull request
      uses: peter-evans/create-pull-request@v6
      with:
        title: Update library to version ${{ steps.read_version.outputs.version }}
        commit-message: Update library to version ${{ steps.read_version.outputs.version }}
        add-paths: ${{ vars.LIB_PATH }}
        body: Pulled in new [library](https://github.com/omarkmu/pz-library) changes.
        base: dev
        branch: update-library
        labels: dependencies,automated
        token: ${{ github.token }}
